### ISSUE TITLE
Configuring different max part numbers for some S3 providers

### ISSUE THREAD

**Issue by Erisa** [ddebeau/zfs_uploader#61]
When setting up zfs_uploader against [Scaleway Object Storage](https://www.scaleway.com/en/object-storage/) (Specifically their `GLACIER` tier), everything worked as expected except with one caveat: The max part number on Scaleway is 1000 rather than the 10000 used by AWS.

This resulted in an error when uploading with the default setup, since it calculated the part sizes based on 10,000 parts and eventually failed due to exceeding Scaleway's limit of 1,000 parts. 

I resolved this for my use-case by simply modifying a number in job.py: https://github.com/Erisa/zfs_uploader/commit/20ed42fa5d64523484c58e62d6f3551dee6c40d2 however I feel that going forward it would be a good idea to allow configuration of this value in the zfs_uploader configuration file, and document it on the README.

You could also detect and change the values based on predefined provider limits, however it still would be nice to have the value in a user-configurable place.

**Comment by ddebeau** [comment]
I also think it would be a good idea to let users set the value. Would you write a PR to add it to the config file and readme?

**Comment by Erisa** [comment]
Sure, I can give that a go! I was planning to look into PRing this earlier but couldn't find the time, I can give it a closer look soonish.
