### ISSUE TITLE
Recursive snapshots

### ISSUE THREAD

**Issue by bridadan** [ddebeau/zfs_uploader#65]
First of all, thank you very much for sharing this project! I'm a newcomer to ZFS and I was able to get started in minutes thanks to the excellent documentation!

As I said before, I'm fairly new to ZFS. I've managed to put together a server with the following datasets:

```sh
$ zfs list
NAME                    USED  AVAIL     REFER  MOUNTPOINT
zfspool                 244G  5.09T      467M  /zfspool
zfspool/bulkstorage     145G  5.09T      145G  /zfspool/bulkstorage
zfspool/vm-100-disk-0     3M  5.09T      120K  -
zfspool/vm-100-disk-1  33.0G  5.12T     3.30G  -
zfspool/vm-102-disk-0  66.0G  5.13T     20.6G  -
zfspool/vm-102-disk-1     3M  5.09T      120K  -
```

My config file looks like this (with redacted info styled `<like this>`):

```sh
[DEFAULT]
bucket_name = <bucket>
region = <region>
access_key = <access key>
secret_key = <secret key>
storage_class = STANDARD
endpoint = <endpoint>

[zfspool]
cron = 0 2 * * *
max_snapshots = 7
max_incremental_backups_per_full = 6
max_backups = 7
```

I naively expected `zfs_uploader` to recursively snapshot and upload backups of each dataset within `zfspool`, however it only did so for the data specifically stored in the `zfspool` mount point that was not part of any of the children.

Is this supported by `zfs_uploader`, or do I need to specify each dataset manually? Ex. `[zfspool/bulkstorage]`, `[zfspool/vm-100-disk-0]`, etc.

Also related, I did find that ZFS supports recursive snapshots, but I haven't tried it yet: https://docs.oracle.com/cd/E19253-01/819-5461/gdfdt/index.html

**Comment by ddebeau** [comment]
Thank you!

While ZFS does support recursively creating snapshots I didn't build in support for it. I would accept a PR that added a configuration option. Off the top of my head you could search for dependent file systems here if the `recursive` option is `True` and then create individual `ZFSjob` objects:

https://github.com/ddebeau/zfs_uploader/blob/c48c1fa8368577d7c4e9f9c4a4e306cdfdc08944/zfs_uploader/config.py#L43-L85

**Comment by bridadan** [comment]
Thanks for the feedback. I started thinking about it more and I realized I probably don't want to do a recursive backup at this time. My config is relatively small and I don't expect it to grow. However, if that changes I'll certainly revisit this. Thanks!
