### ISSUE TITLE
Adaptive storageclass

### ISSUE THREAD

**Issue by andaag** [ddebeau/zfs_uploader#66]
Hi, I'm the author of https://github.com/andaag/zfs-to-glacier/ and I occasionally go hunting for alternative versions, to see if someone has invested more in this problem than me and I can stop maintaining this.

One thing I see you are missing is storage class depending on size. I got a fairly ugly hack here : https://github.com/andaag/zfs-to-glacier/blob/main/src/main.rs#L95 to adjust the storage class to standard in cases where the file size is too small for glacier. (In these cases you pay a premium, and it's actually cheaper with standard storage). 

Glacier minimum billable size is 128kb. Quite a lot of incremental backups can be 1kb, so Standard storage is a very clear winner!

**Comment by ddebeau** [comment]
Hi! I tried to stay as flexible as possible with my storage class implementation. I can't think of a simple solution for setting storage class by size since we support vendors like Backblaze too.
