### ISSUE TITLE
Encrypt snapshots

### ISSUE THREAD

**Issue by LeMaX10** [ddebeau/zfs_uploader#72]
Hello!

Are there any plans to implement encryption of snapshots for unencrypted pools / data sources before uploading to s3?

Example:
```
zfs send pool/dataset@snapshot-name | gpg --symmetric --cipher-algo AES256 -o /path/to/encrypted-snapshot.gpg
```

**Comment by ddebeau** [comment]
Hi! No, I recommend using the native ZFS encryption instead.

**Comment by LeMaX10** [comment]
Thanks!
